version: '3'


services:

    telebot_run:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
#        logging: &logging
#            driver: "json-file"
#            options:
#                max-size: "500m"
